#!/usr/bin/env python
"""Refresh the MACRO_AUTO block of agents/prompts/macro_regime.md from real
economic data (Alpha Vantage), so the analyst's fundamental mapping stays
grounded in current CPI / Fed funds / 10Y yields instead of going stale.

Only the block between <!-- MACRO_AUTO_START --> and <!-- MACRO_AUTO_END --> is
rewritten. The narrative lines (geopolitics, drivers, catalysts) that a human or
the youtube-to-knowhow workflow maintains are left untouched.

Usage:
    python scripts/update_regime.py            # fetch + rewrite the block
    python scripts/update_regime.py --dry-run  # print, do not write

Needs ALPHAVANTAGE_API_KEY in the environment / .env (free key, 25 req/day —
run this at most a few times a day, e.g. weekly via Task Scheduler / cron).
"""
import argparse
import json
import os
import re
import sys
import time
import urllib.request
from datetime import date
from pathlib import Path

try:
    from dotenv import load_dotenv
    load_dotenv()
except Exception:
    pass

API = "https://www.alphavantage.co/query"
REGIME_PATH = Path(__file__).resolve().parent.parent / "agents" / "prompts" / "macro_regime.md"
START = "<!-- MACRO_AUTO_START : generated by scripts/update_regime.py — do not hand-edit between these markers -->"
END = "<!-- MACRO_AUTO_END -->"


def _get(params: dict) -> dict:
    """One Alpha Vantage call with a 1.5s courtesy delay + one rate-limit retry."""
    key = os.getenv("ALPHAVANTAGE_API_KEY")
    if not key:
        sys.exit("ERROR: ALPHAVANTAGE_API_KEY not set (put it in .env). Aborting.")
    qs = "&".join(f"{k}={v}" for k, v in {**params, "apikey": key}.items())
    for attempt in range(2):
        with urllib.request.urlopen(f"{API}?{qs}", timeout=25) as r:
            data = json.loads(r.read().decode())
        if "data" in data:
            return data
        # rate-limited / note → wait and retry once
        msg = data.get("Information") or data.get("Note") or str(data)[:120]
        if attempt == 0:
            print(f"  rate-limited, retrying in 3s... ({msg[:60]})")
            time.sleep(3)
        else:
            sys.exit(f"ERROR fetching {params.get('function')}: {msg}")
    return {}


def _series(fn: str, extra: str = "") -> list[tuple[str, float]]:
    """Return [(date, value)] newest-first, dropping non-numeric ('.') points."""
    params = {"function": fn, "interval": "monthly"}
    if extra:
        k, v = extra.split("=")
        params[k] = v
    out = []
    for row in _get(params).get("data", []):
        try:
            out.append((row["date"], float(row["value"])))
        except (KeyError, ValueError):
            continue
    time.sleep(1.5)  # stay under the free-tier burst limit
    return out


def _pct(new: float, old: float) -> float:
    return (new - old) / old * 100 if old else 0.0


def _yoy_base(series: list[tuple[str, float]]) -> float:
    """Value ~12 months before the latest date (date-aware, gap-tolerant).

    Indexing 12 points back breaks when a month is missing (Alpha Vantage can
    return '.' which we drop), so match the same calendar month one year prior.
    """
    from datetime import datetime
    latest = datetime.strptime(series[0][0], "%Y-%m-%d")
    for d, v in series:
        dt = datetime.strptime(d, "%Y-%m-%d")
        if dt.year == latest.year - 1 and dt.month == latest.month:
            return v
    # fallback: point nearest to exactly 365 days before latest
    return min(series[1:], key=lambda dv:
               abs((latest - datetime.strptime(dv[0], "%Y-%m-%d")).days - 365))[1]


def build_block() -> str:
    print("Fetching CPI / Fed funds / 10Y yield from Alpha Vantage...")
    cpi = _series("CPI")
    fed = _series("FEDERAL_FUNDS_RATE")
    ten = _series("TREASURY_YIELD", "maturity=10year")
    if len(cpi) < 13 or not fed or not ten:
        sys.exit("ERROR: insufficient data returned — leaving file unchanged.")

    # ── CPI: YoY + recent monthly momentum ─────────────────────────
    cpi_yoy = _pct(cpi[0][1], _yoy_base(cpi))
    mm = [_pct(cpi[i][1], cpi[i + 1][1]) for i in range(4)]   # last 4 m/m (newest first)
    recent_mm, prior_mm = (mm[0] + mm[1]) / 2, (mm[2] + mm[3]) / 2
    re_accel = recent_mm > prior_mm and mm[0] > 0.3
    cooling = mm[0] < 0.1

    # ── Fed funds direction (latest vs ~4 months ago) ──────────────
    fed_now = fed[0][1]
    fed_delta = fed_now - fed[min(4, len(fed) - 1)][1]
    fed_dir = "hiking" if fed_delta > 0.10 else "cutting" if fed_delta < -0.10 else "on hold"

    ten_now = ten[0][1]
    ten_dir = "rising" if ten_now - ten[min(5, len(ten) - 1)][1] > 0.05 else \
              "falling" if ten_now - ten[min(5, len(ten) - 1)][1] < -0.05 else "flat"
    real_rate = fed_now - cpi_yoy

    # ── Derive the inflation->gold mapping for THIS regime ─────────
    if fed_dir == "hiking":
        infl = ("- inflation_surprise -> BEARISH gold (Fed hiking to fight inflation, "
                "real yields rising)")
        watch = "- WATCH: a dovish Fed pivot would flip inflation->gold BULLISH"
    elif (re_accel or cpi_yoy >= 3.0) and real_rate < 0:
        infl = ("- inflation_surprise -> BULLISH gold (hot inflation, Fed not hiking, "
                "real policy rate negative)")
        watch = ("- WATCH: a hawkish Fed pivot vs the inflation re-accel would flip "
                 "inflation->gold BEARISH")
    elif cooling:
        infl = ("- inflation_surprise -> default (inflation impulse cooling — fading "
                "tailwind for gold)")
        watch = "- WATCH: re-acceleration would restore the bullish inflation tailwind"
    else:
        infl = "- inflation_surprise -> default gold_factors (no strong regime tilt)"
        watch = ""

    mm_txt = ", ".join(f"{d[:7]} {v:+.2f}%" for d, v in
                       zip([cpi[i][0] for i in range(2)], mm[:2]))
    trend = "re-accel" if re_accel else "cooling" if cooling else "steady"
    data_line = (f"DATA (auto {date.today()}): CPI YoY {cpi_yoy:+.1f}% m/m {trend} "
                 f"({mm_txt}); FedFunds {fed_now:.2f}% {fed_dir}; 10Y {ten_now:.2f}% "
                 f"{ten_dir}; real policy rate {real_rate:+.1f}% "
                 f"({'negative' if real_rate < 0 else 'positive'})")

    body = "\n".join([START, data_line, infl] + ([watch] if watch else []) + [END])
    return body


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true", help="print, do not write")
    args = ap.parse_args()

    block = build_block()
    print("\n--- new MACRO_AUTO block ---")
    print(block)

    text = REGIME_PATH.read_text(encoding="utf-8")
    if START in text and END in text:
        new = re.sub(re.escape(START) + r".*?" + re.escape(END), block, text, flags=re.DOTALL)
    else:
        # markers missing → insert right after REGIME_START
        new = text.replace("<!-- REGIME_START -->", "<!-- REGIME_START -->\n" + block, 1)

    if args.dry_run:
        print("\n[dry-run] macro_regime.md NOT modified.")
        return
    REGIME_PATH.write_text(new, encoding="utf-8")
    print(f"\nUpdated {REGIME_PATH}")


if __name__ == "__main__":
    main()
