#!/usr/bin/env python
"""Refresh the MACRO_AUTO block of agents/prompts/macro_regime.md from real
economic data (Alpha Vantage), so the analyst's fundamental mapping stays
grounded in current CPI / Fed funds / 10Y yields instead of going stale.

Only the block between <!-- MACRO_AUTO_START --> and <!-- MACRO_AUTO_END --> is
rewritten. The narrative lines (geopolitics, drivers, catalysts) that a human or
the youtube-to-knowhow workflow maintains are left untouched.

Usage:
    python scripts/update_regime.py            # fetch + rewrite the block
    python scripts/update_regime.py --dry-run  # print, do not write

Needs ALPHAVANTAGE_API_KEY in the environment / .env (free key, 25 req/day —
run this at most a few times a day, e.g. daily via Task Scheduler / cron).

H1 (auto CATALYSTS + sentiment):
  - CATALYSTS line: reads ForexFactory calendar + data/event_scenarios.json,
    lists ≤2 upcoming HIGH-impact US events with hot/cool gold dirs.
  - sentiment line (TAG-ONLY, no directional verb): emitted only when
    AlphaVantage NEWS_SENTIMENT and news_impact.json AGREE non-neutral.
    Kill switch: REGIME_SENTIMENT_ENABLED=0.

H2 (regime-shift detector):
  - Writes data/regime_state.json with {fed_dir, real_rate_sign, sentiment_tilt}
    monitored tuple + shift flag + history. Fail-soft.
"""
import argparse
import json
import os
import re
import sys
import time
import urllib.request
from datetime import date, datetime, timezone
from pathlib import Path

try:
    from dotenv import load_dotenv
    load_dotenv()
except Exception:
    pass

API = "https://www.alphavantage.co/query"
REGIME_PATH = Path(__file__).resolve().parent.parent / "agents" / "prompts" / "macro_regime.md"
START = "<!-- MACRO_AUTO_START : generated by scripts/update_regime.py — do not hand-edit between these markers -->"
END = "<!-- MACRO_AUTO_END -->"

# ── H1 / H2: project root on sys.path (needed for connectors import) ──────────
_PROJECT_ROOT = str(Path(__file__).resolve().parent.parent)
if _PROJECT_ROOT not in sys.path:
    sys.path.insert(0, _PROJECT_ROOT)

try:
    from connectors.web_news import fetch_forexfactory_calendar as _fetch_calendar
except Exception:
    _fetch_calendar = None  # type: ignore[assignment]

# ── H1 / H2: data file paths ──────────────────────────────────────────────────
EVENT_SCENARIOS_PATH = Path(__file__).resolve().parent.parent / "data" / "event_scenarios.json"
NEWS_IMPACT_PATH     = Path(__file__).resolve().parent.parent / "data" / "news_impact.json"
REGIME_STATE_PATH    = Path(__file__).resolve().parent.parent / "data" / "regime_state.json"

# Maps lowercase event-title substrings → scenario key.
# More-specific needles come first (e.g. "core cpi" before plain "cpi").
_NEEDLE_MAP = {
    "non-farm":       "NFP",
    "nonfarm":        "NFP",
    "core cpi":       "CORE_CPI",
    "core consumer":  "CORE_CPI",
    "cpi":            "CPI",
    "consumer price": "CPI",
    "fomc":           "FOMC",
    "federal funds":  "FOMC",
    "unemployment":   "UNEMPLOYMENT",
    "jobless":        "UNEMPLOYMENT",
    "retail sales":   "RETAIL_SALES",
    "pce":            "PCE",
    "gdp":            "GDP",
}

# Geo-risk keywords for the sentiment tag vocabulary (C12-§2, frozen).
_GEO_KEYWORDS = frozenset({
    "war", "iran", "hormuz", "israel", "tariff", "sanction", "strike",
})


# ── core AV helpers (unchanged from original) ─────────────────────────────────

def _get(params: dict) -> dict:
    """One Alpha Vantage call with a 1.5s courtesy delay + one rate-limit retry."""
    key = os.getenv("ALPHAVANTAGE_API_KEY")
    if not key:
        sys.exit("ERROR: ALPHAVANTAGE_API_KEY not set (put it in .env). Aborting.")
    qs = "&".join(f"{k}={v}" for k, v in {**params, "apikey": key}.items())
    for attempt in range(2):
        with urllib.request.urlopen(f"{API}?{qs}", timeout=25) as r:
            data = json.loads(r.read().decode())
        if "data" in data:
            return data
        # rate-limited / note → wait and retry once
        msg = data.get("Information") or data.get("Note") or str(data)[:120]
        if attempt == 0:
            print(f"  rate-limited, retrying in 3s... ({msg[:60]})")
            time.sleep(3)
        else:
            sys.exit(f"ERROR fetching {params.get('function')}: {msg}")
    return {}


def _series(fn: str, extra: str = "") -> list[tuple[str, float]]:
    """Return [(date, value)] newest-first, dropping non-numeric ('.') points."""
    params = {"function": fn, "interval": "monthly"}
    if extra:
        k, v = extra.split("=")
        params[k] = v
    out = []
    for row in _get(params).get("data", []):
        try:
            out.append((row["date"], float(row["value"])))
        except (KeyError, ValueError):
            continue
    time.sleep(1.5)  # stay under the free-tier burst limit
    return out


def _pct(new: float, old: float) -> float:
    return (new - old) / old * 100 if old else 0.0


def _yoy_base(series: list[tuple[str, float]]) -> float:
    """Value ~12 months before the latest date (date-aware, gap-tolerant).

    Indexing 12 points back breaks when a month is missing (Alpha Vantage can
    return '.' which we drop), so match the same calendar month one year prior.
    """
    from datetime import datetime
    latest = datetime.strptime(series[0][0], "%Y-%m-%d")
    for d, v in series:
        dt = datetime.strptime(d, "%Y-%m-%d")
        if dt.year == latest.year - 1 and dt.month == latest.month:
            return v
    # fallback: point nearest to exactly 365 days before latest
    return min(series[1:], key=lambda dv:
               abs((latest - datetime.strptime(dv[0], "%Y-%m-%d")).days - 365))[1]


# ── H1 helpers ────────────────────────────────────────────────────────────────

def _av_fetch_fail_soft(params: dict):
    """One AV GET — returns parsed JSON dict or None on any error (never exits)."""
    key = os.getenv("ALPHAVANTAGE_API_KEY")
    if not key:
        return None
    qs = "&".join(f"{k}={v}" for k, v in {**params, "apikey": key}.items())
    try:
        with urllib.request.urlopen(f"{API}?{qs}", timeout=25) as r:
            return json.loads(r.read().decode())
    except Exception:
        return None


def _catalysts_line(today: date):
    """Build the CATALYSTS auto-line from ForexFactory calendar + event_scenarios.json.

    Returns a formatted one-liner string, or None when nothing can be built
    (no match, fetch failure, missing scenario file).
    """
    if _fetch_calendar is None:
        return None
    try:
        events = _fetch_calendar(hours_ahead=168, include_all_us=True)
    except Exception:
        return None

    try:
        with open(EVENT_SCENARIOS_PATH, encoding="utf-8") as f:
            scenarios = json.load(f).get("scenarios", {})
    except Exception:
        return None

    now_utc = datetime.now(timezone.utc)

    # Collect upcoming HIGH-impact USD events with a parseable timestamp.
    upcoming = []
    for ev in events:
        if ev.get("currency", "").upper() != "USD":
            continue
        if ev.get("impact", "") != "High":
            continue
        ts_str = ev.get("timestamp_iso", "")
        try:
            ev_dt = datetime.fromisoformat(ts_str)
            if ev_dt.tzinfo is None:
                ev_dt = ev_dt.replace(tzinfo=timezone.utc)
        except Exception:
            continue
        if ev_dt <= now_utc:
            continue
        upcoming.append((ev_dt, ev))

    upcoming.sort(key=lambda x: x[0])  # nearest first

    matched = []
    seen_keys: set = set()
    for ev_dt, ev in upcoming:
        if len(matched) >= 2:
            break
        title_lower = ev.get("title", "").lower()
        scenario_key = None
        for needle, key in _NEEDLE_MAP.items():
            if needle in title_lower:
                scenario_key = key
                break
        if scenario_key is None or scenario_key in seen_keys:
            continue
        sc = scenarios.get(scenario_key)
        if sc is None:
            continue
        hot_dir  = sc.get("hot",  {}).get("dir", "?")
        cool_dir = sc.get("cool", {}).get("dir", "?")
        mm_dd = ev_dt.strftime("%m-%d")
        matched.append(f"{scenario_key} {mm_dd} (hot->{hot_dir} / cool->{cool_dir})")
        seen_keys.add(scenario_key)

    if not matched:
        return None
    return f"- CATALYSTS (auto {today}): {'; '.join(matched)}"


def _sentiment_line_and_tilt(today: date):
    """Build the TAG-ONLY sentiment line and return the internal directional tilt.

    Returns (tilt, line_or_None) where:
      tilt ∈ {bullish, bearish, neutral} — internal direction for H2 shift
        detection only.  NEVER written into the analyst line.
      line_or_None — TAG-ONLY text with NO directional verb (C12-§2 grammar),
        or None when the line is omitted.

    Line is omitted when: kill-switch is on, news_impact neutral, AV unavailable
    (quota/network/missing key), AV or news_impact returns neutral, they disagree,
    or no gold-proxy scores in the AV feed.  Fail-soft on every path.
    """
    if os.getenv("REGIME_SENTIMENT_ENABLED", "1") == "0":
        return ("neutral", None)

    # Source B: data/news_impact.json aggregate score
    try:
        with open(NEWS_IMPACT_PATH, encoding="utf-8") as f:
            ni_data = json.load(f)
        ni_score = float(ni_data.get("aggregate", {}).get("score", 0))
        ni_dir   = "bullish" if ni_score > 10 else "bearish" if ni_score < -10 else "neutral"
        if ni_dir == "neutral":
            return ("neutral", None)
        posts = ni_data.get("posts", [])
    except Exception:
        return ("neutral", None)

    # Source A: AlphaVantage NEWS_SENTIMENT (fail-soft — never sys.exit)
    proxy = os.getenv("REGIME_SENTIMENT_TICKER", "GLD")
    av_data = _av_fetch_fail_soft({
        "function": "NEWS_SENTIMENT",
        "topics":   "economy_monetary,financial_markets",
        "tickers":  proxy,
        "sort":     "LATEST",
        "limit":    "50",
    })
    if av_data is None:
        return ("neutral", None)
    # Rate-limited or informational response → omit (do not exit)
    if "Information" in av_data or "Note" in av_data:
        return ("neutral", None)

    feed = av_data.get("feed", [])
    if not feed:
        return ("neutral", None)

    # Extract per-item score for the gold proxy ticker ONLY.
    # No fallback to overall_sentiment_score (C12-§4, frozen).
    proxy_upper = proxy.upper()
    scores = []
    for item in feed:
        for ts in item.get("ticker_sentiment", []):
            if ts.get("ticker", "").upper() == proxy_upper:
                try:
                    scores.append(float(ts["ticker_sentiment_score"]))
                except (KeyError, ValueError):
                    pass
                break  # one entry per ticker per feed item

    if not scores:
        # Gold proxy absent from feed → no reading → omit line
        return ("neutral", None)

    av_score = sum(scores) / len(scores)
    av_dir = "bullish" if av_score >= 0.15 else "bearish" if av_score <= -0.15 else "neutral"
    if av_dir == "neutral":
        return ("neutral", None)

    # Agreement rule (C12-§2, frozen): both non-neutral and equal
    if av_dir != ni_dir:
        return ("neutral", None)

    tilt = av_dir  # internal direction for H2; NOT printed

    # Geo tag (C12-§2 frozen vocabulary): scan news_impact posts
    geo_hit = any(
        kw in post.get("text", "").lower()
        for post in posts
        for kw in _GEO_KEYWORDS
    )
    tag = "risk-bid geopolitics" if geo_hit else "macro tone"
    ni_int = int(ni_score)
    line = (
        f"- sentiment (auto {today}): {tag} — "
        f"AV & news_impact agree (AV {av_score:+.2f}, ni {ni_int:+d})"
    )
    return (tilt, line)


# ── H2 helper ─────────────────────────────────────────────────────────────────

def _write_regime_state(build_result: dict) -> None:
    """Detect regime shifts and write data/regime_state.json (C12-§3). Fail-soft.

    Monitored tuple: {fed_dir, real_rate_sign, sentiment_tilt}.
    Real-rate sign dead-band: |real_rate| < 0.1 → carry previous sign.
    Sentiment debounce: flip counted only when NEW tilt is non-neutral.
    Atomic write (tmp + os.replace); leaves prior file intact on any error.
    """
    try:
        fed_dir        = build_result["fed_dir"]
        real_rate      = build_result["real_rate"]
        cpi_yoy        = build_result["cpi_yoy"]
        fed_funds      = build_result["fed_funds"]
        sentiment_tilt = build_result["sentiment_tilt"]
        now_iso = (
            datetime.now(timezone.utc)
            .isoformat(timespec="seconds")
            .replace("+00:00", "Z")
        )

        # Real-rate sign with dead-band (C12-§3)
        if abs(real_rate) >= 0.1:
            real_rate_sign = "negative" if real_rate < 0 else "positive"
        else:
            real_rate_sign = None  # will be resolved from prior state

        # Load previous state (missing file → no prior)
        prior = None
        try:
            with open(REGIME_STATE_PATH, encoding="utf-8") as f:
                prior = json.load(f)
        except Exception:
            pass

        # Resolve dead-band: use prior sign if we are within ±0.1 band
        if real_rate_sign is None:
            real_rate_sign = (
                (prior or {}).get("real_rate_sign")
                or ("negative" if real_rate < 0 else "positive")
            )

        # Shift detection
        shift_kind = []
        if prior:
            if fed_dir != prior.get("fed_dir"):
                shift_kind.append("fed_dir_flip")
            if real_rate_sign != prior.get("real_rate_sign"):
                shift_kind.append("real_rate_sign_flip")
            # Sentiment debounce: count flip only when NEW tilt is non-neutral (C12-§3)
            prev_tilt = prior.get("sentiment_tilt", "neutral")
            if sentiment_tilt != prev_tilt and sentiment_tilt in {"bullish", "bearish"}:
                shift_kind.append("sentiment_tilt_flip")

        shift_active = bool(shift_kind)

        prior_from = None
        if shift_active and prior:
            prior_from = {
                "fed_dir":        prior.get("fed_dir"),
                "real_rate_sign": prior.get("real_rate_sign"),
                "sentiment_tilt": prior.get("sentiment_tilt", "neutral"),
            }

        # History capped at 10 entries
        history = list((prior or {}).get("history", []))
        if shift_active:
            history.append({
                "date": datetime.now(timezone.utc).strftime("%Y-%m-%d"),
                "kind": shift_kind,
            })
        history = history[-10:]

        state = {
            "ok":             True,
            "updated":        now_iso,
            "fed_dir":        fed_dir,
            "real_rate_sign": real_rate_sign,
            "sentiment_tilt": sentiment_tilt,
            "cpi_yoy":        round(cpi_yoy, 2),
            "fed_funds":      round(fed_funds, 2),
            "real_rate":      round(real_rate, 2),
            "shift": {
                "active": shift_active,
                "kind":   shift_kind,
                "from":   prior_from,
                "to": {
                    "fed_dir":        fed_dir,
                    "real_rate_sign": real_rate_sign,
                    "sentiment_tilt": sentiment_tilt,
                } if shift_active else None,
                "since": now_iso if shift_active else None,
            },
            "history": history,
        }

        # Atomic write: write to .tmp then replace (safe for concurrent readers)
        tmp_path = REGIME_STATE_PATH.with_suffix(".tmp")
        tmp_path.write_text(json.dumps(state, indent=2), encoding="utf-8")
        tmp_path.replace(REGIME_STATE_PATH)
        print(
            f"Written {REGIME_STATE_PATH.name} "
            f"(shift.active={shift_active}, kind={shift_kind})"
        )

    except Exception as exc:
        print(f"[warn] _write_regime_state failed (non-fatal): {exc}")


# ── main block builder ────────────────────────────────────────────────────────

def build_block() -> dict:
    """Fetch macro data and build the MACRO_AUTO block.

    Returns a dict:
      "block"          – MACRO_AUTO text (START…END, inclusive)
      "fed_dir"        – hiking | cutting | on hold
      "real_rate"      – float (FedFunds − CPI YoY)
      "cpi_yoy"        – float
      "fed_funds"      – float
      "sentiment_tilt" – bullish | bearish | neutral  (H2 only; not in analyst line)
    """
    print("Fetching CPI / Fed funds / 10Y yield from Alpha Vantage...")
    cpi = _series("CPI")
    fed = _series("FEDERAL_FUNDS_RATE")
    ten = _series("TREASURY_YIELD", "maturity=10year")
    if len(cpi) < 13 or not fed or not ten:
        sys.exit("ERROR: insufficient data returned — leaving file unchanged.")

    # ── CPI: YoY + recent monthly momentum ─────────────────────────
    cpi_yoy = _pct(cpi[0][1], _yoy_base(cpi))
    mm = [_pct(cpi[i][1], cpi[i + 1][1]) for i in range(4)]   # last 4 m/m (newest first)
    recent_mm, prior_mm = (mm[0] + mm[1]) / 2, (mm[2] + mm[3]) / 2
    re_accel = recent_mm > prior_mm and mm[0] > 0.3
    cooling = mm[0] < 0.1

    # ── Fed funds direction (latest vs ~4 months ago) ──────────────
    fed_now = fed[0][1]
    fed_delta = fed_now - fed[min(4, len(fed) - 1)][1]
    fed_dir = "hiking" if fed_delta > 0.10 else "cutting" if fed_delta < -0.10 else "on hold"

    ten_now = ten[0][1]
    ten_dir = "rising" if ten_now - ten[min(5, len(ten) - 1)][1] > 0.05 else \
              "falling" if ten_now - ten[min(5, len(ten) - 1)][1] < -0.05 else "flat"
    real_rate = fed_now - cpi_yoy

    # ── Derive the inflation->gold mapping for THIS regime ─────────
    if fed_dir == "hiking":
        infl = ("- inflation_surprise -> BEARISH gold (Fed hiking to fight inflation, "
                "real yields rising)")
        watch = "- WATCH: a dovish Fed pivot would flip inflation->gold BULLISH"
    elif (re_accel or cpi_yoy >= 3.0) and real_rate < 0:
        infl = ("- inflation_surprise -> BULLISH gold (hot inflation, Fed not hiking, "
                "real policy rate negative)")
        watch = ("- WATCH: a hawkish Fed pivot vs the inflation re-accel would flip "
                 "inflation->gold BEARISH")
    elif cooling:
        infl = ("- inflation_surprise -> default (inflation impulse cooling — fading "
                "tailwind for gold)")
        watch = "- WATCH: re-acceleration would restore the bullish inflation tailwind"
    else:
        infl = "- inflation_surprise -> default gold_factors (no strong regime tilt)"
        watch = ""

    mm_txt = ", ".join(f"{d[:7]} {v:+.2f}%" for d, v in
                       zip([cpi[i][0] for i in range(2)], mm[:2]))
    trend = "re-accel" if re_accel else "cooling" if cooling else "steady"
    data_line = (f"DATA (auto {date.today()}): CPI YoY {cpi_yoy:+.1f}% m/m {trend} "
                 f"({mm_txt}); FedFunds {fed_now:.2f}% {fed_dir}; 10Y {ten_now:.2f}% "
                 f"{ten_dir}; real policy rate {real_rate:+.1f}% "
                 f"({'negative' if real_rate < 0 else 'positive'})")

    # ── [H1] CATALYSTS + sentiment (each independently fail-soft) ──────────
    catalysts = _catalysts_line(date.today())
    tilt, sentiment = _sentiment_line_and_tilt(date.today())

    body_lines = [START, data_line, infl]
    if watch:
        body_lines.append(watch)
    if catalysts:
        body_lines.append(catalysts)
    if sentiment:
        body_lines.append(sentiment)
    body_lines.append(END)

    return {
        "block":          "\n".join(body_lines),
        "fed_dir":        fed_dir,
        "real_rate":      real_rate,
        "cpi_yoy":        cpi_yoy,
        "fed_funds":      fed_now,
        "sentiment_tilt": tilt,
    }


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--dry-run", action="store_true", help="print, do not write")
    args = ap.parse_args()

    result = build_block()
    block  = result["block"]
    print("\n--- new MACRO_AUTO block ---")
    print(block)

    text = REGIME_PATH.read_text(encoding="utf-8")
    if START in text and END in text:
        new = re.sub(re.escape(START) + r".*?" + re.escape(END), block, text, flags=re.DOTALL)
    else:
        # markers missing → insert right after REGIME_START
        new = text.replace("<!-- REGIME_START -->", "<!-- REGIME_START -->\n" + block, 1)

    if args.dry_run:
        print("\n[dry-run] macro_regime.md NOT modified.")
        print("[dry-run] regime_state.json NOT written.")
        return

    REGIME_PATH.write_text(new, encoding="utf-8")
    print(f"\nUpdated {REGIME_PATH}")

    # [H2] Write regime shift state — fail-soft, does not affect macro_regime.md
    _write_regime_state(result)


if __name__ == "__main__":
    main()
